name: Build and Deploy Staging
on:
  workflow_run:
    workflows: ["Build and Deploy"]
    branches: [master]
    types: completed
  push:
    branches:
      - staging

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Download build artifact
        uses: actions/download-artifact@v2
        id: download
        with: 
          name: build-artifact-staging

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: Deploy to Staging
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./build
          target-folder: ./staging
