name: Build and Deploy Staging
on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: change package.json
        run: sed -i 's/ghPagesTest\//ghPagesTest\/staging\//g' package.json

      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          ref: staging
            
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to Staging
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./build
          target-folder: ./staging
