name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: change package.json
        run: sed -i 's/ghPagesTest\/staging\//ghPagesTest\//g' package.json

      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./build
          target-folder: ./live
          
