name: PR Build
on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Change package.json for live
        if: ${{ github.ref == 'refs/heads/master' }}
        run: sed -i 's/ghPagesTest\/staging\//ghPagesTest\//g' package.json

      - name: Change package.json for staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        run: sed -i 's/ghPagesTest\//ghPagesTest\/staging\//g' package.json

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-${{ github.head_ref && github.ref }}
          path: ./build
